Feiten = [
    "Een wolk weegt ongeveer een miljoen ton.",
    "Giraffen worden 30 keer vaker door de bliksem getroffen dan mensen.",
    "Identieke tweelingen hebben niet dezelfde vingerafdrukken.",
    "De rotatiesnelheid van de aarde verandert.",
    "Je brein eet zichzelf voortdurend op.",
    "De grootste gefossiliseerde dinosauruspoep is meer dan 30 cm lang.",
    "De gemiddelde kleur van het universum heet 'Cosmic latte'.",
    "Dieren kunnen tijd anders ervaren dan mensen.",
    "Water is mogelijk niet nat.",
    "Een kip leefde ooit 18 maanden zonder kop.",
    "Alle bacteriën op aarde op elkaar gestapeld zouden 10 miljard lichtjaar bereiken.",
    "Een stropdas dragen kan de bloedtoevoer naar de hersenen met 7,5% verminderen.",
    "De angst voor lange woorden heet Hippopotomonstrosesquippedaliophobia.",
    "De oudste hond ter wereld werd 29,5 jaar oud.",
    "De oudste kat ter wereld werd 38 jaar en drie dagen oud.",
    "De zon maakt geluid, maar wij kunnen het niet horen.",
    "De Mount Everest is niet de hoogste berg op aarde.",
    "Ons zonnestelsel heeft een 'muur'.",
    "Octopussen hebben geen tentakels, maar armen.",
    "De meeste wereldkaarten zijn incorrect.",
    "NASA heeft een deel van de maanlanding in scène gezet.",
    "Kometen ruiken naar rotte eieren.",
    "De magnetische polen van de aarde verschuiven.",
    "Je kunt daadwerkelijk sterven van het lachen.",
    "Kettingzagen werden oorspronkelijk uitgevonden voor bevallingen.",
    "Mieren hebben geen longen.",
    "De T. rex had waarschijnlijk veren.",
    "Voetbalteams in rode shirts spelen beter.",
    "Windturbines doden tussen de 10.000 en 100.000 vogels per jaar in het VK.",
    "Slakken hebben tanden, soms wel 12.000.",
    "Geluid kan negatieve decibels hebben.",
    "Een paard heeft normaal meer dan één paardenkracht.",
    "Je handtekening kan persoonlijkheidskenmerken onthullen.",
    "Eén op de 18 mensen heeft een derde tepel.",
    "Bananen zijn radioactief.",
    "Er bestaat niet zoiets als een rechte lijn.",
    "Dove mensen gebruiken gebarentaal in hun slaap.",
    "Finland is het gelukkigste land ter wereld.",
    "Nijlpaarden kunnen niet zwemmen.",
    "De maan lijkt ondersteboven op het zuidelijk halfrond.",
    "Je kunt jojoën in de ruimte.",
    "Niet alleen planten fotosynthetiseren.",
    "Je kunt vergevorderd zwanger zijn zonder het te weten.",
    "Bacteriën op je huid veroorzaken jeuk.",
    "Zeesterren hebben geen lichamen, alleen een hoofd.",
    "Iemand had eens 45 dagen lang obstipatie.",
    "Je reist elke dag 2,5 miljoen km rond de zon zonder het te beseffen.",
    "Vissen vormen ordelijke rijen in noodsituaties.",
    "Er zijn meer bacteriële cellen in je lichaam dan menselijke cellen.",
    "De meeste rode katten zijn mannelijk."
]
