# Liste der Fakten auf Deutsch
Fakten = [
    "Eine Wolke wiegt etwa eine Million Tonnen.",
    "Eine typische Wolke hat ein Volumen von etwa 1 km3 und eine Dichte von etwa 1,003 kg pro m3.",
    "Das ist etwa 0,4 % weniger als die umgebende Luft, wodurch sie schweben kann.",
    "Giraffen werden 30-mal häufiger vom Blitz getroffen als Menschen.",
    "Es gibt nur fünf gut dokumentierte tödliche Blitzschläge auf Giraffen zwischen 1996 und 2010.",
    "Aufgrund der damaligen Population von 140.000 ergibt sich eine Sterblichkeitsrate von etwa 0,003 pro tausend Giraffen pro Jahr.",
    "Das ist 30-mal mehr als bei Menschen.",
    "Eineiige Zwillinge haben nicht die gleichen Fingerabdrücke.",
    "Umweltfaktoren während der Entwicklung im Mutterleib beeinflussen ihre Fingerabdrücke.",
    "Die Erdrotation verändert ihre Geschwindigkeit.",
    "Tatsächlich verlangsamt sie sich, was bedeutet, dass sich die Tageslänge im Durchschnitt um etwa 1,8 Sekunden pro Jahrhundert verlängert.",
    "Vor 600 Millionen Jahren dauerte ein Tag nur 21 Stunden.",
    "Dein Gehirn frisst sich ständig selbst.",
    "Dieser Prozess nennt sich Phagozytose, bei dem Zellen kleinere Zellen oder Moleküle umschließen und konsumieren.",
    "Phagozytose hilft, die graue Substanz zu erhalten.",
    "Das größte Stück versteinerter Dinosaurierkot, das jemals gefunden wurde, ist über 30 cm lang.",
    "Es hat ein Volumen von mehr als zwei Litern.",
    "Es wird angenommen, dass es von einem Tyrannosaurus rex stammt.",
    "Die durchschnittliche Farbe des Universums wird als 'kosmischer Latte' bezeichnet.",
    "In einer Studie aus dem Jahr 2002 fanden Astronomen heraus, dass das Licht der Galaxien im Durchschnitt eine beige Farbe aufweist.",
    "Tiere können Zeit anders wahrnehmen als Menschen.",
    "Kleinere Tiere erleben die Welt langsamer als Menschen.",
    "Salamander und Eidechsen nehmen Zeit langsamer wahr als Katzen und Hunde.",
    "Dies liegt daran, dass die Zeitwahrnehmung davon abhängt, wie schnell das Gehirn eingehende Informationen verarbeiten kann.",
    "Wasser ist möglicherweise nicht nass.",
    "Die meisten Wissenschaftler definieren Nässe als die Fähigkeit einer Flüssigkeit, mit einer festen Oberfläche in Kontakt zu bleiben.",
    "Das bedeutet, dass Wasser selbst nicht nass ist, aber andere Objekte nass machen kann.",
    "Ein Huhn lebte einmal 18 Monate ohne Kopf.",
    "Der Fall von Mike, dem Huhn, wurde in den 1940er Jahren in den USA dokumentiert.",
    "Er überlebte, weil seine Halsvene und ein großer Teil seines Hirnstamms intakt blieben.",
    "Dadurch hatte er genügend Gehirnfunktion zum Überleben.",
    "In den meisten Fällen stirbt ein kopfloses Huhn innerhalb weniger Minuten."
]
