facts = [
    "A cloud weighs around a million tonnes.",
    "Giraffes are 30 times more likely to get hit by lightning than people.",
    "Identical twins don’t have the same fingerprints.",
    "Earth’s rotation is changing speed.",
    "Your brain is constantly eating itself.",
    "The largest piece of fossilized dinosaur poo discovered is over 30cm long.",
    "The Universe's average colour is called 'Cosmic latte'.",
    "Animals can experience time differently from humans.",
    "Water might not be wet.",
    "A chicken once lived for 18 months without a head.",
    "All the world’s bacteria stacked on top of each other would stretch for 10 billion light-years.",
    "Wearing a tie can reduce blood flow to the brain by 7.5 per cent.",
    "The fear of long words is called Hippopotomonstrosesquippedaliophobia.",
    "The world’s oldest dog lived to 29.5 years old.",
    "The world’s oldest cat lived to 38 years and three days old.",
    "The Sun makes a sound but we can't hear it.",
    "Mount Everest isn't the tallest mountain on Earth.",
    "Our solar system has a wall.",
    "Octopuses don’t actually have tentacles.",
    "Most maps of the world are wrong.",
    "NASA genuinely faked part of the Moon landing.",
    "Comets smell like rotten eggs.",
    "Earth’s poles are moving.",
    "You can actually die laughing.",
    "Chainsaws were first invented for childbirth.",
    "Ants don’t have lungs.",
    "The T. rex likely had feathers.",
    "Football teams wearing red kits play better.",
    "Wind turbines kill between 10,000 and 100,000 birds each year in the UK.",
    "Snails have teeth.",
    "Sound can be minus decibels.",
    "A horse normally has more than one horsepower.",
    "Your signature could reveal personality traits.",
    "One in 18 people have a third nipple.",
    "Bananas are radioactive.",
    "There’s no such thing as a straight line.",
    "Deaf people are known to use sign language in their sleep.",
    "Finland is the happiest country on Earth.",
    "Hippos can’t swim.",
    "The Moon looks upside down in the Southern Hemisphere.",
    "You can yo-yo in space.",
    "Not only plants photosynthesize.",
    "You can be heavily pregnant and not realise.",
    "Bacteria on your skin cause your itches.",
    "Starfish don’t have bodies.",
    "Somebody has been constipated for 45 days.",
    "You travel 2.5 million km a day around the Sun without realising.",
    "Fish form orderly queues in emergencies.",
    "There are more bacterial cells in your body than human cells.",
    "Most ginger cats are male."
]
