Faits = [
    "Un nuage pèse environ un million de tonnes.",
    "Les girafes ont 30 fois plus de chances d'être frappées par la foudre que les humains.",
    "Les jumeaux identiques n'ont pas les mêmes empreintes digitales.",
    "La rotation de la Terre change de vitesse et ralentit avec le temps.",
    "Votre cerveau se mange constamment lui-même par un processus appelé phagocytose.",
    "Le plus grand excrément fossilisé de dinosaure découvert mesure plus de 30 cm de long.",
    "La couleur moyenne de l'Univers est appelée 'Latte cosmique'.",
    "Les animaux peuvent percevoir le temps différemment des humains.",
    "L'eau pourrait ne pas être humide, car l'humidité est définie comme l'interaction d'un liquide avec une surface solide.",
    "Un poulet a vécu pendant 18 mois sans tête.",
    "Toutes les bactéries du monde empilées atteindraient 10 milliards d'années-lumière.",
    "Porter une cravate peut réduire le flux sanguin vers le cerveau de 7,5 %.",
    "La peur des mots longs s'appelle l'hippopotomonstrosesquippedaliophobie.",
    "Le chien le plus vieux du monde a vécu jusqu'à 29,5 ans.",
    "Le chat le plus vieux du monde a vécu 38 ans et 3 jours.",
    "Le Soleil émet un son, mais nous ne pouvons pas l'entendre.",
    "Le mont Everest n'est pas la plus haute montagne de la Terre.",
    "Notre système solaire a un mur appelé l'héliopause.",
    "Les poulpes n'ont pas de tentacules, mais des bras.",
    "La plupart des cartes du monde sont incorrectes en raison de la projection de Mercator.",
    "La NASA a effectivement falsifié une partie de l'alunissage, mais pas les premiers pas.",
    "Les comètes sentent l'oeuf pourri et l'ammoniac.",
    "Les pôles magnétiques de la Terre se déplacent et un renversement pourrait être imminent.",
    "Il est possible de mourir de rire.",
    "La tronçonneuse a été inventée pour l'accouchement.",
    "Les fourmis n'ont pas de poumons mais respirent par de petits orifices appelés spiracles.",
    "Le T-Rex avait probablement des plumes.",
    "Les équipes de football portant du rouge jouent mieux en moyenne.",
    "Les éoliennes tuent des milliers d'oiseaux chaque année, mais peindre une pale en noir peut réduire les collisions.",
    "Les escargots ont entre 1 000 et 12 000 dents.",
    "Le son peut avoir des décibels négatifs dans des chambres anéchoïques.",
    "Un cheval peut produire jusqu'à 24 chevaux-vapeur.",
    "Votre signature pourrait révéler des traits de personnalité.",
    "Une personne sur 18 a un troisième mamelon.",
    "Les bananes sont radioactives en raison de leur teneur en potassium-40.",
    "Il n'existe pas de ligne droite parfaite dans la nature.",
    "Les personnes sourdes peuvent utiliser le langage des signes pendant leur sommeil.",
    "La Finlande est le pays le plus heureux du monde depuis six ans consécutifs.",
    "Les hippopotames ne savent pas nager mais marchent sous l'eau.",
    "La Lune semble à l'envers dans l'hémisphère sud.",
    "Il est possible de faire du yo-yo dans l'espace.",
    "D'autres organismes que les plantes peuvent photosynthétiser, comme certains insectes et algues.",
    "Une femme peut être enceinte sans s'en rendre compte jusqu'à l'accouchement.",
    "Les bactéries sur votre peau peuvent provoquer des démangeaisons.",
    "Les étoiles de mer n'ont pas de corps distinct, leur tête est tout leur corps.",
    "Quelqu'un a été constipé pendant 45 jours.",
    "Vous voyagez 2,5 millions de km par jour autour du Soleil sans vous en rendre compte.",
    "Les poissons peuvent former des files d'attente en cas d'urgence.",
    "Il y a plus de cellules bactériennes dans votre corps que de cellules humaines.",
    "La plupart des chats roux sont des mâles.",
]
